# Generated by Django 2.1.7 on 2019-05-14 11:02

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20190514_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(default=1, upload_to='article/%Y%m%d'),
            preserve_default=False,
        ),
    ]
