# Generated by Django 2.1.7 on 2019-05-14 14:16

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_articlepost_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='article/%Y%m%d'),
        ),
    ]
