# Generated by Django 2.1.7 on 2019-05-15 03:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20190514_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='body1',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
