# Generated by Django 2.1.7 on 2019-05-16 04:13

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20190515_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='body1',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
