# Generated by Django 2.1.7 on 2019-05-20 07:00

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(blank=True)),
                ('body1', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('avatar', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='book/%Y%m%d')),
            ],
            options={
                'ordering': ('-created_time',),
            },
        ),
    ]
