# Generated by Django 2.1.7 on 2019-05-22 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videopost',
            name='video_url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
